### PR TITLE
Extending support to Mongoid 5

### PR DESCRIPTION
**Pull request by Mohakjuneja**
Hey guys! I've made the changes suggested by @tboerger. The tests are all green and this should extend support to Mongoid 5 version

### CODE REVIEW

**Comment by tboerger** [comment]
:+1: so it looks like it is compatible to mongoid 5

**Comment by Mohakjuneja** [comment]
Awesome! Please merge them in that case. And thanks for your help. Really appreciate it

**Comment by tboerger** [comment]
@Mohakjuneja waiting also for a response of @johnnyshields as he's still actively using this gem ;)

**Comment by johnnyshields** [comment]
Great, nice job on your first PR @Mohakjuneja !

**Comment by Mohakjuneja** [comment]
Thank you @johnnyshields :) All credit to you guys!

**Pull request merged**
